site_name: metalsmith-ssgs
repo_url: https://gitlab.com/metalsmith-ssgs/metalsmith-ssgs
site_author: Antonio Hernandez ahdiaz@gmail.com
site_description: A static site generator based in metalsmith and a collection of plugins.
copyright: MIT License. Copyright © 2016 Antonio Hernandez <ahdiaz@gmail.com>
theme: readthedocs
site_dir: _docs_build
nav:
  - index.md
  - settings.md
  - getting-started.md
  - plugins.md